In [1]:
le-4

NameError: name 'le' is not defined

In [2]:
1e-4

0.0001

In [3]:
2e-4

0.0002

In [4]:
import numpy as np

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
a=np.random.uniform(-1,1,[5,5])

In [9]:
a

array([[-0.43764195, -0.19979596, -0.75121151, -0.44499749, -0.63186357],
       [ 0.59695867,  0.00782512,  0.2111416 , -0.09948829, -0.15086921],
       [ 0.342     , -0.74247813, -0.3509978 , -0.69481651, -0.46515059],
       [ 0.72085733, -0.0316107 ,  0.65810052,  0.55912433,  0.44416881],
       [ 0.03800694,  0.91849222,  0.86926733,  0.76421123,  0.35638531]])

In [10]:
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=x*x

In [11]:
a

array([[  1.91530478e-01,   3.99184276e-02,   5.64318731e-01,
          1.98022765e-01,   3.99251571e-01],
       [  3.56359648e-01,   6.12324780e-05,   4.45807748e-02,
          9.89792025e-03,   2.27615195e-02],
       [  1.16964001e-01,   5.51273777e-01,   1.23199452e-01,
          4.82769980e-01,   2.16365074e-01],
       [  5.19635291e-01,   9.99236591e-04,   4.33096288e-01,
          3.12620019e-01,   1.97285928e-01],
       [  1.44452785e-03,   8.43627964e-01,   7.55625693e-01,
          5.84018797e-01,   1.27010492e-01]])

In [13]:
(-0.43764195)**2

0.1915304763998025